import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

import styles from '../styles/Home.module.css'
import { useState } from 'react'
const tickets = [{
  id: 0,
  title: 'this is a title',
  description: 'small description of show',
  cost: 20,
  quantity: 0
},{
  id: 1,
  title: 'other show',
  description: 'small description of show',
  cost: 45,
  quantity: 0
}, {
  id: 2,
  title: 'main show',
  description: 'small description of show',
  cost: 10,
  quantity: 0
}]

export default function Home() {
  const [shows, setShows] = useState(tickets);

  function addTickets(e) {
    if(e.target.value < 0) return;
    
    const updateShows = shows.map(show => {
      if(show.id !== parseInt(e.target.getAttribute('index'))) {
        return show;
      } else {
        return {
          ...show,
          quantity: e.target.value
        }
      }
    })

    setShows(updateShows);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Ticket App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">the store</a>
        </h1>

        <p className={styles.description}>
          Select one of our curated shows below
        </p>

        <div className={styles.grid}>
          
        { shows.map( show => (
            <a className={styles.card} key={show.id}>
              <h2>{show.title}</h2>
              <input index={show.id} type='number' value={show.quantity} onChange={addTickets} />
              <p>{show.description}</p>
            </a>
          ))}
        </div>

        <Link href={ { 
          pathname: "/checkout",
          query: { 
            shows: JSON.stringify(shows) 
          }}} >
            Checkout
         </Link>
         
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
